### PR TITLE
Fix/#148-rename-tables-to-lowercase

### LINKED ISSUE #148: Rename tables to lowercase
Uppercase table names force the use of quotation marks in an SQL, which is inconvinient.
E.g. the table `Containers` can only be queried using
```sql
SELECT * FROM "Containers"
```
whereas the table `containers` can be queried as such
```sql
SELECT * from containers
```

This is currently breaking the frontend.

### PR DESCRIPTION
**Pull request by smnws**
closes #148

### CODE REVIEW

File: Proxy/internal/database/model/model.go [hunk 1]
```diff
@@ -7,15 +7,15 @@ import (
...
+	bun.BaseModel `bun:"table:clusters"`
 	ID            int       `bun:"id,autoincrement"`
 	ClusterID     int       `bun:"cluster_id"`
 	Timestamp     time.Time `bun:"timestamp,notnull"`
 	Name          string    `bun:"name"`
 }
 
 type Service struct {
-	bun.BaseModel     `bun:"Services"`
+	bun.BaseModel     `bun:"services"`
```
Comment (vringar) [inline Proxy/internal/database/model/model.go:18]: Why do we use `bun:"table:clusters"` sometimes and `bun:"services"` in other times?

**Comment by vringar** [comment]
Okay, I've adjusted the Explorer to work with the upper case table names for this release.
So  now we need to update
https://github.com/amosproj/amos2023ss04-kubernetes-inventory-taker/blob/ddbd9df4fc5ae33ca955228e5f9b4141ef33bfcc/Explorer/src/lib/db.ts#L50-L77
